# Generated by Django 4.2.4 on 2023-08-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
