# Generated by Django 4.2.4 on 2023-08-26 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_track', '0004_habit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_track.habit')),
            ],
        ),
    ]
