# Generated by Django 4.2.4 on 2023-08-27 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_track', '0007_alter_habit_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 19, 24, 2, 90347)),
        ),
    ]
