# Generated by Django 4.2.4 on 2023-08-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Productive', 'Productive'), ('Unproductive', 'Unproductive'), ('Neutral', 'Neutral')], max_length=20)),
            ],
        ),
    ]
