# Generated by Django 4.2.4 on 2023-08-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrack',
            name='date_for',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
